[workspace.package]
version = "1.0.0"
edition = "2024"
authors = ["Jiang <hackfree@msn.com>"]

[workspace]
resolver = "2"
members = ["app/src-tauri"]
# exclude = ["app"]
# default-members = ["app"]

[workspace.dependencies]
